package output

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"

	"r3f-trend-spotter/pkg/domain"
)

const reportTemplate = `# Trend Report - {{ .Date }}

Here are the top trending topics relevant to your interests.

{{ range .Trends }}
## {{ .Title }} ({{ printf "%.1f" .Score }} pts)
**Source**: {{ .Source }}  
**URL**: {{ .URL }}

{{ if .Summary }}
> **AI Summary**: {{ .Summary }}
{{ end }}

{{ .Description }}

---
{{ end }}

Generated by r3f-trend-spotter
`

type ReportData struct {
	Date   string
	Trends []domain.Trend
}

// GenerateMarkdownReport creates a markdown file with the trend summary.
func GenerateMarkdownReport(trends []domain.Trend, outputDir string) (string, error) {
	if len(trends) == 0 {
		return "", fmt.Errorf("no trends to report")
	}

	tmpl, err := template.New("report").Parse(reportTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	dateStr := time.Now().Format("2006-01-02")
	fileName := fmt.Sprintf("trend-report-%s.md", dateStr)
	fullPath := filepath.Join(outputDir, fileName)

	// Ensure directory exists
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create directory: %w", err)
	}

	f, err := os.Create(fullPath)
	if err != nil {
		return "", fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	data := ReportData{
		Date:   dateStr,
		Trends: trends,
	}

	if err := tmpl.Execute(f, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return fullPath, nil
}
